

export interface productdetail{
  productId:number;
  name:string;
  description:string;
  price:number;
  owner:string;
  color:string;
  quantity:number;
  isStock:boolean;
  image:string
}

export const productData : productdetail[] = [
    {
      productId:1,
      name:"Hammer",
      description:"LoremIpsum",
      price:200,
      owner:"Owens",
      color:"Silver",
      quantity:400,
      isStock:true,
      image:"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F0%2F05%2FTools-hammer.svg%2F768px-Tools-hammer.svg.png&f=1&nofb=1"
    },
    {
      productId:2,
      name:"Hammer",
      description:"",
      price:200,
      owner:"Owens",
      color:"Silver",
      quantity:400,
      isStock:true,
      image:"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F0%2F05%2FTools-hammer.svg%2F768px-Tools-hammer.svg.png&f=1&nofb=1"
    },
    {
      productId:3,
      name:"Hammer",
      description:"",
      price:200,
      owner:"Owens",
      color:"Silver",
      quantity:400,
      isStock:true,
      image:"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F0%2F05%2FTools-hammer.svg%2F768px-Tools-hammer.svg.png&f=1&nofb=1"
    },
    {
      productId:4,
      name:"Hammer",
      description:"",
      price:200,
      owner:"Owens",
      color:"Silver",
      quantity:400,
      isStock:true,
      image:"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F0%2F05%2FTools-hammer.svg%2F768px-Tools-hammer.svg.png&f=1&nofb=1"
    },
    {
      productId:5,
      name:"Hammer",
      description:"",
      price:200,
      owner:"Owens",
      color:"Silver",
      quantity:400,
      isStock:true,
      image:"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F0%2F05%2FTools-hammer.svg%2F768px-Tools-hammer.svg.png&f=1&nofb=1"
    }
]
